<a href="https://colab.research.google.com/github/Balajilp/Pytorch-Learning/blob/main/Back_Propogation_using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Back propogation using pytorch

In [1]:
import torch

In [3]:
# we need to keep 'requires_grad=True' in order to do back propogation 
x = torch.tensor(4.0, requires_grad=True)
x

tensor(4., requires_grad=True)

In [4]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [5]:
## formula for backpropogation/derivative is in this case it is y = 2*x ...general derivative formula x**n = n*x**n-1
y.backward()

In [7]:
# print the derivative/backpropogated weight
print(x.grad)

tensor(8.)


## in neural networks more complex operations can happen for that we can try matrix derivative

In [11]:
# NOTE : requires_grad parameter requires floating point numbers only so we can set dtype=flot
lst = [[2, 3, 1], [4, 5, 3], [7, 6, 4]]
torch_input = torch.tensor(lst, dtype=torch.float, requires_grad=True)

In [12]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [16]:
### y = x**3 + x**2
### y = 3x**2 + 2x
y = torch_input**3 + torch_input**2
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [17]:
z=y.sum()

In [18]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [19]:
z.backward()

In [23]:
## this is how complex neural networks weights calculated
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])